POST http://localhost:3001/login/
Content-Type: application/json

{
    "username_or_email":"satya",
    "password":"Satya@2021",
    "is_username":true
}


###

GET http://localhost:3001/history?search_q=
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjQsInVzZXJuYW1lIjoic2F0eWEiLCJlbWFpbCI6InNhdHlhQGdtYWlsLmNvbSIsImlhdCI6MTcwMDM5OTkwMn0.e4OQ1LtTCseMT5rTdtWBsHjYhDrHA-xaHIvhWlfWtok
