POST http://localhost:3001/register/
Content-Type: application/json

{
    "username": "Jyothi",
    "email": "jyothichongala@gmail.com",
    "password":"Jyothi@2021"
}

###

POST http://localhost:3001/login/
Content-Type: application/json

{
    "username_or_email": "jaiteja",
    "password":"Jaiteja@2021",
    "is_username":true
}

###

GET http://localhost:3001/profile
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjE2LCJ1c2VybmFtZSI6ImphaXRlamEiLCJlbWFpbCI6ImNob25nYWxhdGVqYTEyMzRAZ21haWwuY29tIiwiaWF0IjoxNjk4MzI3Njk1fQ.I9_6akfpgqEYAfOeC3-doNbt61fp9zTBErSwzHPrI3I



###
GET http://localhost:3001/bookmarks
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjE2LCJ1c2VybmFtZSI6ImphaXRlamEiLCJlbWFpbCI6ImNob25nYWxhdGVqYTEyMzRAZ21haWwuY29tIiwiaWF0IjoxNjk4MzI3Njk1fQ.I9_6akfpgqEYAfOeC3-doNbt61fp9zTBErSwzHPrI3I



###

GET http://localhost:3001/history
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjE2LCJ1c2VybmFtZSI6ImphaXRlamEiLCJlbWFpbCI6ImNob25nYWxhdGVqYTEyMzRAZ21haWwuY29tIiwiaWF0IjoxNjk4MzI3Njk1fQ.I9_6akfpgqEYAfOeC3-doNbt61fp9zTBErSwzHPrI3I



###
GET http://localhost:3001/history
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjE2LCJ1c2VybmFtZSI6ImphaXRlamEiLCJlbWFpbCI6ImNob25nYWxhdGVqYTEyMzRAZ21haWwuY29tIiwiaWF0IjoxNjk4MzI3Njk1fQ.I9_6akfpgqEYAfOeC3-doNbt61fp9zTBErSwzHPrI3I


